@startuml Diagrama_de_clases_zona
class Zone{
    - id
    - name
    - location : Location
    - radius
}

class Delivery{
    - id
    - personId
    - location : Location
    - radius
    - status
}

class Location{
    - latitud
    - longitud
}

Zone --> Location
Delivery --> Location
@enduml